### ISSUE TITLE
GHC 9.2.1 Support

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#1184]
We should update to the new GHC release soon as it adds dot notation (`get #name user => user.name`).

There's some progress already on https://github.com/digitallyinduced/ihp/pull/1175 but some dependencies are not working yet.

**Comment by neongreen** [comment]
HSE might not support the dot notation, though. (But I haven't checked.)

**Comment by mpscholten** [comment]
In that case we should wait a little bit until it's supported. The dot notation is the main reason for upgrading :)

**Comment by neongreen** [comment]
HSE is not developed anymore and hasn't been for a while:

> Dan Burton is currently keeping haskell-src-exts on life support. If you are interested in more actively making improvements to this package, please make your interests known.
>
> You might want to try ghc-lib-parser instead.

**Comment by mpscholten** [comment]
ok then we need to switch 👍  more work than expected :)

**Comment by zacwood9** [comment]
Yeah this is going to be quite an undertaking 😅 just tried setting up a fresh project (not IHP, just cabal init) and I found lots of common libraries are not building for 9.2. 

Until the ecosystem catches up (HLS doesn't event fully support 9.0) it may be worth considering the [record-dot-preprocessor](https://hackage.haskell.org/package/record-dot-preprocessor). They use that in the "Simple Haskell Handbook" book I'm reading and it seems to work well. Especially with IHP since we have auto generated SetField instances

**Comment by neongreen** [comment]
Yeah, using [`recordDotPreprocessorOnFragment`](https://hackage.haskell.org/package/record-dot-preprocessor-0.2.12/docs/RecordDotPreprocessor-Lib.html#v:recordDotPreprocessorOnFragment) could actually work (and normal RDP for the rest of the code).

**Comment by mpscholten** [comment]
This is now available on master 👍
