### ISSUE TITLE
IHP Job Dashboard should use the normal IHP Pagination

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#1198]
Right now the IHP Job Dashboard [implements it's own pagination functionality](https://github.com/digitallyinduced/ihp/blob/master/IHP/Job/Dashboard/Utils.hs#L8). The pagination module was added to IHP after the job dashboard.

[To simplify things it would be nice if the Job Dashboard's pagination is replaced with the standard IHP pagination functionality.](https://github.com/digitallyinduced/ihp/blob/master/IHP/Job/Dashboard/View.hs#L114)

**Comment by oclbdk** [comment]
I'd like to confirm whether an API-breaking change is necessary and get thoughts on a proposal for jobs that implement `TableViewable`.

I numbered my questions with "**Q#**" to make them easier to find.

**Q1.** How do the `TableViewable` jobs get rendered? `makeDashboardSectionFromTableViewable` doesn't seem to be called anywhere.

# Existing Functions

* The `getPage` pagination function for `TableViewable`: https://github.com/digitallyinduced/ihp/blob/master/IHP/Job/Dashboard/Types.hs#L52
* The `paginateWithOptions` IHP pagination function: https://github.com/digitallyinduced/ihp/blob/master/IHP/Pagination/ControllerFunctions.hs#L90

# Discrepancy

The legacy `getPage` interface is expected to return results with an arbitrary implementation (not necessarily a query builder).

The `paginateWithOptions` function receives a query builder and returns a paginated form for the caller to `fetch`.

# Proposal

**Q2.** Would it make sense to replace `getPage` in `TableViewable` with an interface based around query builders and pagination options?

```hs
class TableViewable a where

    ...

    -- remove the following

    getPage :: (?context :: ControllerContext, ?modelContext :: ModelContext) => Int -> Int -> IO [a]

    -- add the following

    queryForListPage :: forall controller table queryBuilderProvider joinRegister .
        ( ?context :: ControllerContext
        , ?modelContext :: ModelContext
        , KnownSymbol table
        , HasQueryBuilder queryBuilderProvider joinRegister) =>
        -> queryBuilderProvider table

    paginationOptionsForListPage :: IHP.Pagination.Types.Options
    paginationOptionsForListPage = IHP.Pagination.ControllerFunctions.defaultPaginationOptions
```

## Index View

**Q3.** Should we change the `getIndex` function to also work with query builders so it matches the interface for the list page?for the list page?

**Comment by zacwood9** [comment]
Thank you for the detailed write up! A nice blast from the past diving back into this code :-)

Q1. `makeDashboardSectionFromTableViewable` is indeed never called directly from the library - this function is intended to be a helper for writing custom implementations of `DisplayableJob` used in the appliaction. For example, from my project:
```haskell
-- first implement TableViewable, using a wrapper to bring in additional data
instance TableViewable (IncludeWrapper "bandId" InitialScrapeJob) where
    modelTableName = tableName @InitialScrapeJob
    tableTitle = tableName @InitialScrapeJob |> columnNameToFieldLabel
    tableHeaders = ["Band", "Updated at", "Status", ""]
    ...

instance DisplayableJob InitialScrapeJob where
   -- use the TableViewable helper functions along with the above instance
    makeDashboardSection = makeDashboardSectionFromTableViewable @(IncludeWrapper "bandId" InitialScrapeJob)
    makePageView = makeListPageFromTableViewable @(IncludeWrapper "bandId" InitialScrapeJob)
   ...
``` 
So, `TableViewable` itself is actually not necessary for the job dashboard, all of the rendering is done [using the `DisplayableJob` instance.](https://github.com/digitallyinduced/ihp/blob/master/IHP/Job/Dashboard.hs#L226) `TableViewable` exists solely as a helper for reducing code duplication when implementing dashboards for custom jobs. If the `TableViewable` helper functions (`makeDashboardSectionFromTableViewable`, `makeDashboardSectionFromTableViewable`) don't fit your use case, (e.g. you don't want to display jobs in a table format) you can always just implement the `DisplayableJob` instance without the helpers.

Q2 + Q3. Because of this ability to easily opt-out, I'd fully support a breaking change to the `TableViewable`  API to include these better defaults. The idea behind the type class and its helpers is to provide a way to keep the standard table view in the default dashboard, but to extend the table with additional fields. Changing the API to be more `QueryBuilder` centric would be a great move and would do a better job at fulfilling its purpose of easily creating `DisplayableJob` instances.
