### ISSUE TITLE
Put HSX on hackage

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#132]

**Comment by simonmichael** [comment]
As I'm sure you know, here's the original package: http://hackage.haskell.org/package/hsx
and the successor: http://hackage.haskell.org/package/hsx2hs .

**Comment by mpscholten** [comment]
To avoid the naming issue we could call the new package `ihp-hsx` or `ihp-html`. What do you think?

**Comment by simonmichael** [comment]
I [wonder](https://www.reddit.com/r/haskell/comments/hee4r4/ihp_is_a_modern_batteriesincluded_web_framework/fvso86b/) is your hsx completely new then ? I just assumed it was the same package I used some years ago.

**Comment by mpscholten** [comment]
Our HSX is completely independent of the existing solutions. It has been custom build just for IHP. We called it HSX because this sounds familiar to people who have previously worked with react :)

**Comment by gasi** [comment]
I would love to use IHP’s HSX as a standalone library. I work on https://zoomhub.net/, a Haskell powered web (https://github.com/zoomhub/zoomhub). Although I admire IHP and its goals, I’m already invested in Servant (since 2016). However, HSX could be a big win for existing projects that haven’t started with IHP.

**Comment by mpscholten** [comment]
IHP's HSX is available as it's own package now on Hackage via https://hackage.haskell.org/package/ihp-hsx-0.18.0 👍
