### ISSUE TITLE
Inconsistent `pathTo` result when using `breadcrumbLink`

### ISSUE THREAD

**Issue by amitaibu** [digitallyinduced/ihp#1335]
Let's say we have

```haskell
instance HasPath StaticController where
    pathTo WelcomeAction = "/"
```

When we call `pathTo` directly the route is correct, but when invoking it via `breadcrumbLink`, we still get the old URL.

```
<p>URL (OK): {pathTo WelcomeAction}</p>
<p>URL (Wrong): {show $ breadcrumbLink "Home" WelcomeAction}</p>
```

HTML:
![Selection_999(631)](https://user-images.githubusercontent.com/125707/150991111-6f1ce2a0-bccf-4257-a5dc-2c05b71506b7.jpg)

**Comment by mpscholten** [comment]
Likely caused by the type signature `breadcrumbLink :: (Show controller, AutoRoute controller) => Html -> controller -> BreadcrumbItem`. The `pathTo` call in that function will then always [use this](https://github.com/digitallyinduced/ihp/blob/master/IHP/RouterSupport.hs#L451) type class.

Instead the type signature should use the more generic `HasPath` class, like this:

```haskell
breadcrumbLink :: (Show controller, HasPath controller) => Html -> controller -> BreadcrumbItem
```
