### ISSUE TITLE
Improve Example App to Include Authentication & Authorization

### ISSUE THREAD

**Issue by GeoffOs** [digitallyinduced/ihp#166]
Enhance the example Application (1)  to include the details contained in the guide (2) - though the instruction also need to include how to add the initial user.

  1 - https://github.com/digitallyinduced/ihp-blog-example-app
  2 - https://ihp.digitallyinduced.com/Guide/authentication.html

**Comment by mpscholten** [comment]
There is now an `auth` branch on the `ihp-blog-example-app`: https://github.com/digitallyinduced/ihp-blog-example-app/blob/master/README.md#auth :)

**Comment by mpscholten** [comment]
This has been fixed by now. The example app now includes an authentication example. The documentation now also contains instructions to create the first user. There's also a new too `hash-password` to generate a password hash from a plaintext password.

If you think something is missing, let me know :)
