### ISSUE TITLE
IHP Contributor Calls

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#1843]
Followup on https://github.com/digitallyinduced/ihp/issues/1818

The IHP contributor calls are every two weeks Friday 16:00 CET.

Open questions:
- is a different day of week better?
- is a different time better?
- Should we keep it bi-weekly or do it every month?

**Comment by amitaibu** [comment]
IMO once every two months is ideal.

**Comment by rvarun11** [comment]
Friday 16:00 CET works for me.  

I think if we have a lot of items on the agenda every one or two weeks then we should go for bi-weekly meetings, otherwise a monthly meeting would make sense. The problem with a monthly meeting though is that if we miss some contributors due to unavailability then we miss them for at least two months.

**Comment by mpscholten** [comment]
Moved the meeting to a monthly interval for now 👍
