### ISSUE TITLE
New project does not compile

### ISSUE THREAD

**Issue by HugoPeters1024** [digitallyinduced/ihp#394]
I've followed the getting started guide closely. But when I run the ` ./start` command I do get a working developer panel at 8001 but the app at 8000 throws the following error:

```
Web/Types.hs:8:1
    Could not find module `Generated.Types'
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
8 | import Generated.Types
  | ^^^^^^^^^^^^^^^^^^^^^^
```

Any idea what could be happening here? I assumed that the `./start`  command drops to a nix env internally or do I have to activate it myself in some way?

**Comment by mpscholten** [comment]
Can you try to make a file change (like adding a new line) to `Application/Schema.sql` while `./start` is running? This will trigger a recompile of `Generated.Types`. Can you share the output that happens in the console where `./start` while you do the file change?

**Comment by HugoPeters1024** [comment]
Thanks for the quick response! Making a change to the Schema file (I just added a newline) doesn't change anything. The full output of the start script is as follows:

```
direnv: loading ~/ihp-test/test/.envrc
direnv: export ~PATH
GHCi, version 8.8.3: https://www.haskell.org/ghc/  :? for help
*** WARNING: .ghci is writable by someone else, IGNORING!
Suggested fix: execute 'chmod go-w .ghci'
Prelude> Prelude> Prelude ClassyPrelude> [1 of 4] Compiling Application.Helper.Controller ( Application/Helper/Controller.hs, interpreted )
[2 of 4] Compiling Web.Types        ( Web/Types.hs, interpreted )

Web/Types.hs:2:1: error:
    Could not load module `IHP.Prelude'
    It is a member of the hidden package `ihp-0.1.0.0'.
    You can run `:set -package ihp' to expose it.
    (Note: this unloads all the modules in the current scope.)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
2 | import IHP.Prelude
  | ^^^^^^^^^^^^^^^^^^

Web/Types.hs:3:1: error:
    Could not load module `IHP.Controller.Session'
    It is a member of the hidden package `ihp-0.1.0.0'.
    You can run `:set -package ihp' to expose it.
    (Note: this unloads all the modules in the current scope.)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
3 | import qualified IHP.Controller.Session
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Types.hs:4:1: error:
    Could not load module `IHP.ControllerSupport'
    It is a member of the hidden package `ihp-0.1.0.0'.
    You can run `:set -package ihp' to expose it.
    (Note: this unloads all the modules in the current scope.)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
4 | import qualified IHP.ControllerSupport as ControllerSupport
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Types.hs:5:1: error:
    Could not load module `IHP.ModelSupport'
    It is a member of the hidden package `ihp-0.1.0.0'.
    You can run `:set -package ihp' to expose it.
    (Note: this unloads all the modules in the current scope.)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
5 | import IHP.ModelSupport
  | ^^^^^^^^^^^^^^^^^^^^^^^

Web/Types.hs:7:1: error:
    Could not load module `IHP.ViewSupport'
    It is a member of the hidden package `ihp-0.1.0.0'.
    You can run `:set -package ihp' to expose it.
    (Note: this unloads all the modules in the current scope.)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
7 | import IHP.ViewSupport
  | ^^^^^^^^^^^^^^^^^^^^^^

Web/Types.hs:8:1: error:
    Could not find module `Generated.Types'
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
8 | import Generated.Types
  | ^^^^^^^^^^^^^^^^^^^^^^
Failed, one module loaded.
```

**Comment by mpscholten** [comment]
I think it’s related to the problem with loading the .ghci `help
*** WARNING: .ghci is writable by someone else, IGNORING!
Suggested fix: execute 'chmod go-w .ghci`. Can you try to run that chmod?

**Comment by HugoPeters1024** [comment]
The warning is now gone but the issue remains. The start command does give some different output now.

```
direnv: loading ~/ihp-test/test/.envrc
direnv: export ~PATH
GHCi, version 8.8.3: https://www.haskell.org/ghc/  :? for help
*** Exception: build/ihp-lib/applicationGhciConfig: hGetContents: invalid argument (invalid byte sequence)
Loaded GHCi configuration from /home/hugo/ihp-test/test/.ghci
Prelude> Prelude> Prelude ClassyPrelude> [1 of 4] Compiling Application.Helper.Controller ( Application/Helper/Controller.hs, interpreted )
[2 of 4] Compiling Web.Types        ( Web/Types.hs, interpreted )

Web/Types.hs:2:1: error:
    Could not load module `IHP.Prelude'
    It is a member of the hidden package `ihp-0.1.0.0'.
    You can run `:set -package ihp' to expose it.
    (Note: this unloads all the modules in the current scope.)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
2 | import IHP.Prelude
  | ^^^^^^^^^^^^^^^^^^

....
The rest stayed the same
```

**Comment by mpscholten** [comment]
This is an encoding issue which we have in the latest release
can you copy the following and put it into the .ghci file in your repo:

:set -i.
:set -iConfig
:set -ibuild
:set -iIHP
:set -threaded
:set -XOverloadedStrings
:set -XNoImplicitPrelude
:set -XImplicitParams
:set -XRank2Types
:set -XDisambiguateRecordFields
:set -XNamedFieldPuns
:set -XDuplicateRecordFields
:set -XOverloadedLabels
:set -XFlexibleContexts
:set -XTypeSynonymInstances
:set -XFlexibleInstances
:set -XQuasiQuotes
:set -XTypeFamilies
:set -XPackageImports
:set -XScopedTypeVariables
:set -XRecordWildCards
:set -XTypeApplications
:set -XDataKinds
:set -XInstanceSigs
:set -XDeriveGeneric
:set -XMultiParamTypeClasses
:set -XTypeOperators
:set -XUndecidableInstances
:set -Wno-unsafe -Wno-name-shadowing -Wno-monomorphism-restriction -Wno-safe -Wno-missing-local-signatures -Wno-missing-home-modules
:set -XDeriveDataTypeable
:set -XLambdaCase
:set -XDefaultSignatures
:set -XEmptyDataDeriving
:set -XBangPatterns
:set -XBlockArguments
:set -XMultiWayIf
:set -XFunctionalDependencies
:set -package ihp
:set -package typerep-map
:set -fbyte-code
:set -Wno-partial-type-signatures
:set -XPartialTypeSignatures
:set -XStandaloneDeriving
:set -XDerivingVia
:set -Werror=missing-fields
:set -fwarn-incomplete-patterns

After that try to run ./start again. This issue will be fixed with the next release coming tomorrow:)

**Comment by HugoPeters1024** [comment]
It's working now! Thanks so much for the quick help, I'm really excited to play around with this framework!
