### ISSUE TITLE
Docu: "Using IHP with Emacs"

### ISSUE THREAD

**Issue by themmes** [digitallyinduced/ihp#415]
Inspired by the other issue of Using IHP with VIM (https://github.com/digitallyinduced/ihp/issues/347), I thought I might pitch in to write something about using it with Emacs. However, it would be nice if other emacs users could share their experience so far!

https://ihp.digitallyinduced.com/Guide/editors.html

**Comment by nicu-chiciuc** [comment]
I just started to dip my toes into both IHP and Doom Emacs and any examples of a nice setup would be great. Doom seems to make it more straightforward, I had to uncomment `lsp` and `(haskell +lsp)` in the `init.el` file but I guess something is not right. My guess is that it might be related to `nix` and the fact that the incorrect `GHC` version is picked.

**Comment by themmes** [comment]
Hi @nicu-chiciuc, thanks for chiming in. So far I have nothing specific to IHP in my emacs setup. Things I've added to my (vanilla emacs) setup are:
- nix-mode
- haskell-mode
- ghc-company (if you use company)

things to improve:
- add emacs support for the error log links (the links that bring you to the exact location)
- fix hsx in haskell mode

I believe @mpscholten often runs the dev server in ghc, I personally haven't tried it that way.

**Comment by mpscholten** [comment]
> My guess is that it might be related to nix and the fact that the incorrect GHC version is picked.

Maybe emacs is not picking up the right PATH variable :) Try out [`emacs-direnv`](https://github.com/wbolster/emacs-direnv).

**Comment by unhammer** [comment]
I haven't tried nix-mode, but emacs-direnv gives you the right PATH to ghci. This makes it easy to use the repl from haskell-mode, and lets dante-mode start a repl in order to show squiggles on the errors and enable dante-type-at and xref-find-definition (if you just add the .dir-locals.el described in https://github.com/digitallyinduced/ihp/pull/464 )

-----

hsx support in haskell-mode is kind of spotty – on my Emacs, when it sees hsx, it seems to try to render that with nxml, but after `|]` it halfway forgets how to render Haskell for a while:
![bilde](https://user-images.githubusercontent.com/56868/96092831-af789f80-0ecb-11eb-9034-112f45f101d2.png)
There have been lots of of issues on quasiquoting: https://github.com/haskell/haskell-mode/issues?q=quasiquote
It may be easier to just turn off the "smart" quasiquote highlighting with `(setq haskell-font-lock-quasi-quote-modes nil)` (or add `(haskell-font-lock-quasi-quote-modes . nil)` to .dir-locals.el) which just syntax-highlights them as opaque strings.

-----

I did try lsp with the language server as an alternative to dante, but gave up on getting it to work. I believe dante is currently easier to get started with, though it provides less features, while last time I tried lsp the language server required quite a bit more memory to run (one area where nix can't solve the "it works on my machine" issue!).

**Comment by unhammer** [comment]
I'm running [lsp in emacs](https://github.com/digitallyinduced/ihp/compare/master...unhammer:doc-emacs-lsp?expand=1) now, seems to work, but I have to run it in a wrapper that sets `ulimit -Sv unlimited` or it keeps hitting some virtual memory limit. I don't know if that's a solution for other people (if so, it might make sense to make a `haskell-language-server-wrapper-wrapper` that sets reasonable usage limits), but if it's only a problem for me maybe not worth it.

**Comment by unhammer** [comment]
There is https://ihp.digitallyinduced.com/Guide/editors.html#using-ihp-with-emacs now, should this be closed?

**Comment by mpscholten** [comment]
Yes, let's close this 👍
