### ISSUE TITLE
`ihp-new` takes a lot of time

### ISSUE THREAD

**Issue by raptazure** [digitallyinduced/ihp#551]
Thanks for this wonderful framework. But when I am running `ihp-new ihp-test-project` as said in [CONTRIBUTING.md](https://github.com/raptazure/ihp/blob/master/CONTRIBUTING.md), it takes more than an hour to finish. Seems that it is compiling everything. Is there a way to make it a little bit faster?
![image](https://user-images.githubusercontent.com/44319278/99360995-62ce1d00-28ec-11eb-81f3-b6582fba6001.png)

**Comment by mpscholten** [comment]
Hey, thanks for reporting this. We usually have prebuild binaries that should be downloaded instead of precompiling everything.

What macOS version are you using?
Can you run [the Auto Troubleshooting script](https://ihp.digitallyinduced.com/Guide/troubleshooting.html)? This might detect possible errors with the cachix binary cache

**Comment by raptazure** [comment]
Oh, It was solved by removing `~/.config/nix/nix.conf` and run `ihp-new` again, which will generate a new nix config file. It turned out to be caused by replacing substituters with [tuna nix mirror](https://discourse.nixos.org/t/announcing-tuna-nix-mirror/6144). After the original config is back, everything works fine :)  

Thanks a lot for your responding!
