### ISSUE TITLE
currentUser not available in view

### ISSUE THREAD

**Issue by kodeFant** [digitallyinduced/ihp#641]
Per the recent context changes, `currentUser` seems to no longer be accessible in views. This seems to not have been updated in the docs about getting the current user in the [authentication section](https://ihp.digitallyinduced.com/Guide/authentication.html#accessing-the-current-user)

Getting this message when trying to use it directly in a view.

```
• Overlapping instances for ToHtml a0
    arising from a use of ‘toHtml’
  Matching instances:
    instance [overlappable] Show a => ToHtml a
      -- Defined in ‘IHP.HtmlSupport.ToHtml’
    instance ToHtml (MarkupM ()) -- Defined in ‘IHP.HtmlSupport.ToHtml’
    instance ToHtml ByteString -- Defined in ‘IHP.HtmlSupport.ToHtml’
    ...plus four others
    (use -fprint-potential-instances to see them all)
  (The choice depends on the instantiation of ‘a0’
   To pick the first instance above, use IncoherentInstances
   when compiling the other instance declarations)
• In the expression:
    toHtml ((get (fromLabel @"email")) currentUser)
  In the fourth argument of ‘makeParent’, namely
    ‘[string [],
      (applyAttributes
         ((((makeParent "h1") "<h1") "</h1>")
            [string "Your MainQuest membership"]))
        [\ h_aGQlg
           -> (h_aGQlg
                 ! ((attribute "class") " class="")
                     (cs (pack "box-header") :: AttributeValue))],
      string [],
      (applyAttributes
         ((((makeParent "ul") "<ul") "</ul>")
            [toHtml (renderSubscriptions subscription)]))
        [],
      string [], toHtml (renderInvoices invoices),
      toHtml renderUserActions,
      toHtml ((get (fromLabel @"email")) currentUser)]’
  In the first argument of ‘applyAttributes’, namely
    ‘((((makeParent "div") "<div") "</div>")
        [string [],
         (applyAttributes
            ((((makeParent "h1") "<h1") "</h1>")
               [string "Your MainQuest membership"]))
           [\ h_aGQlg
              -> (h_aGQlg
                    ! ((attribute "class") " class="")
                        (cs (pack "box-header") :: AttributeValue))],
         string [],
         (applyAttributes
            ((((makeParent "ul") "<ul") "</ul>")
               [toHtml (renderSubscriptions subscription)]))
           [],
         string [], toHtml (renderInvoices invoices),
         toHtml renderUserActions,
         toHtml ((get (fromLabel @"email")) currentUser)])’
```

I'm solving it now by getting the `Maybe User` from the `frozenContext`.

Not sure if it's a bug or the documentation should be updated, so posted it here before attempting a pull request :)

**Comment by s0kil** [comment]
From what I understand the `currentUser` is only available inside a controller, to access the current user in a view, you could do [`fromFrozenContext @(Maybe User)`](https://ihp.digitallyinduced.com/Guide/recipes.html#making-a-dynamic-loginlogout-button)

**Comment by mpscholten** [comment]
`currentUser` and `currentUserOrNothing` are [still available](https://github.com/digitallyinduced/ihp/blob/master/IHP/LoginSupport/Helper/View.hs#L11).

I think the issue is mainly that GHC cannot find out the user type. We have that `CurrentUserRecord` for getting this to work. You likely have defined `type instance CurrentUserRecord = User` inside `Application.Helper.Controller`. The problem is that the views don't load the  `Application.Helper.Controller` module, and so the `CurrentUserRecord` is not yet set to a specific type.

I'd consider this an issue with IHP (so let's keep this issue open even when the workaround below fixes the problem). We need to move these type family definitions somewhere else where both views and controllers have access to them.

Workaround:

Append a `import Application.Helper.Controller ()` to your `Application.Helper.View`. This will make sure that `type instance CurrentUserRecord = User` is defined when the views are compiled.

**Comment by mpscholten** [comment]
Turns out I already created an issue for this https://github.com/digitallyinduced/ihp/issues/603#issue-764192347 :)

**Comment by mpscholten** [comment]
I found a clean solution for this: Move the `type instance CurrentUserRecord = User` definition to `Web.Types` :) This will be the new default as of the next IHP release.

Implemented in https://github.com/digitallyinduced/ihp/pull/660
