### ISSUE TITLE
Creating An Enum And Table With The Same Name Throws Error In DevServer

### ISSUE THREAD

**Issue by s0kil** [digitallyinduced/ihp#783]
Error:

```
NoData.MonoTraversable.headEx: empty
CallStack (from HasCallStack):
  error, called at src/Data/MonoTraversable.hs:397:28 in mono-traversable-1.0.15.1-AwDeddwIKE6FHgqF6f6LB9:Data.MonoTraversable
 match in record selector values
```

Related: Error when viewing an enum/table with the same name at `ShowEnum?enumName=Stuff` or `ShowTable?tableName=Stuff`
The error is:
```
No match in record selector values
No match in record selector unsafeGetCreateTable
```

**Comment by Alexander-Block** [comment]
I would like to work on this issue if that is okay (I find the ideas behind IHP very interesting and would like to contribute to it and learn more about its inner workings by helping to resolve bugs). 

It seems to me that there are two separate problems behind this issue. The easier one is that it should not be possible to create tables or enum types with a name that is already taken by another table or enum type in the Schema Designer. I think that this can be solved by adding validation logic that is similar to the one I added to ensure uniqueness of enum values with PR #809 . I will prepare a PR for this as soon as possible. 

The errors of the form `No match in record selector <x>`, however, have a more general source. The type `Statement` is defined in `IHP.IDE.SchemaDesigner.Types` as a sum type of records:
```haskell
data Statement
    =
    -- | CREATE TABLE name ( columns );
      StatementCreateTable { unsafeGetCreateTable :: CreateTable }
    -- | CREATE TYPE name AS ENUM ( values );
    | CreateEnumType { name :: Text, values :: [Text] }
    -- | CREATE EXTENSION IF NOT EXISTS "name";
    | CreateExtension { name :: Text, ifNotExists :: Bool }
    -- | ALTER TABLE tableName ADD CONSTRAINT constraintName constraint;
    | AddConstraint { tableName :: Text, constraintName :: Text, constraint :: Constraint }
    | UnknownStatement { raw :: Text }
    | Comment { content :: Text }
    -- | CREATE INDEX indexName ON tableName (columnName);
    | CreateIndex { indexName :: Text, tableName :: Text, columnNames :: [Text] }
    deriving (Eq, Show)
```
A common pattern in the code for the Schema Designer seems to be the following:
```haskell
action UpdateColumnAction = do 
  ...
  let table = findStatementByName tableName statements
  let columns = maybe [] (get #columns . unsafeGetCreateTable) table
  ...
```
Here `findStatementByName` returns a `Statement` representing the first SQL statement in a given list of statements creating a table or an enum type of a given name. Obviously this leads to problems when we expect a table but get an enum type, since, e.g., `unsafeGetCreateTable` is partial and throws `No match in record selector unsafeGetCreateTable` on input of the form `CreateEnumType { .. }`.

Probably it is an option not to make any changes to tackle this problem directly, since as was noted by @mpscholten in PR #118, where `findStatementByName` was introduced to consolidate `findTableByName` and `findEnumByName`: 
> You cannot have a enum named like a table at the same time in Postgres

However, in light of this issue, I propose the following change to safely handle situations in which this assumption (for whatever reason) does not hold. It would be possible to rework `Statement` to get rid of partial selectors as follows:
```haskell
data Statement
    =
      StatementCreateTable CreateTable
    | StatementCreateEnumType CreateEnumType
    | StatementCreateExtension CreateExtension
    | StatementAddConstraint AddConstraint
    | UnknownStatement Text
    | Comment Text
    | StatementCreateIndex CreateIndex
    deriving (Eq, Show)

data CreateEnumType = CreateEnumType { name :: Text, values :: [Text] }
data CreateExtension = CreateExtension { name :: Text, ifNotExists :: Bool }
...
```
Then all current uses of `findTableByName` where we expect exactly a table or an enum type could be replaced by functions of the following form: 
```haskell
findCreateTableByName :: Text -> [Statement] -> Maybe CreateTable
findCreateEnumTypeByName :: Text -> [Statement] -> Maybe CreateEnumType
```
The above code snippet for `action UpdateColumnAction` would then be transformed into the following:
```haskell
action UpdateColumnAction = do 
  ...
  let table = findCreateTableByName tableName statements
  let columns = maybe [] (get #columns) table
  ...
```
This would eliminate the use of partial selectors. A drawback would be more verbose pattern matching in some other parts of the code. 
What do the devs think about this? Does this change make sense?

**Comment by mpscholten** [comment]
Thanks for taking a look at this :)

I think this has been discussed before. With `StatementCreateTable { unsafeGetCreateTable :: CreateTable }` we even kind of did the first step.

> A drawback would be more verbose pattern matching in some other parts of the code.

I worry about this as well. Especially on the sql parser.

On the other side I could help simplify the controller code by removing `unsafeGetCreateTable`s and replacing some pattern matches.

So in general I'm open for this change 👍

**Comment by Alexander-Block** [comment]
Thank you for this feedback. 

> So in general I'm open for this change 👍

In this case I will try to implement this change, so that we can see whether the drawbacks outweigh the benefits or the other way around.

**Comment by mpscholten** [comment]
Fixed via https://github.com/digitallyinduced/ihp/pull/820
