### ISSUE TITLE
unsafePerformIO in Log and read ?context.

### ISSUE THREAD

**Issue by Montmorency** [digitallyinduced/ihp#846]
In most cases I think the (relatively few) calls to `unsafePerformIO` in IHP are reading from the implicit context variable in views however in [IHP/Log.hs](https://github.com/digitallyinduced/ihp/blob/d98c3d6eb8145d859c9ce461e7d1367be5be7337/IHP/Log.hs#L114) it looks like unsafePerformIO is triggering something a little more like a side effect.

The documentation suggests: "Use {-# NOINLINE foo #-} as a pragma on any function foo that calls unsafePerformIO. If the call is inlined, the I/O may be performed more than once."

The latest version of GHC has a recent ticket relating to the the [no-inline trick as well](https://gitlab.haskell.org/ghc/ghc/-/issues/19413). Would it be worthwhile at least marking any functions as NOINLINE to be on the safe side? Happy to make a PR.

**Comment by mpscholten** [comment]
👍  Good points

We should look into why `makeRequestLogger` is using `unsafePerformIO` at all. Maybe we can just make it a normal IO function?

cc @zacwood9

**Comment by zacwood9** [comment]
No reason, just for convenience purposes when defining your config. Should be no problem to make it an IO function - you'll just need to change the  [default request logger](https://github.com/digitallyinduced/ihp/blob/master/IHP/FrameworkConfig.hs#L109) to bind properly with liftIO. If we do change that, make sure to document the change prominently since anyone using the function in their config will have to change their config code as well.

**Comment by mpscholten** [comment]
Let's give this a try 👍

**Comment by Montmorency** [comment]
https://github.com/digitallyinduced/ihp/pull/847

**Comment by Montmorency** [comment]
Tested logging again following Docs configuration setup. I didn't need to make any Doc changes to get logger running in test app.

**Comment by s0kil** [comment]
Already merged: https://github.com/digitallyinduced/ihp/pull/847
