### ISSUE TITLE
`paginate` function does not work with joined queries

### ISSUE THREAD

**Issue by GarrisonJ** [digitallyinduced/ihp#990]
When I try to use the `paginate` function with a joined query I get a type error that `JoinQueryBuilderWrapper` is not a `QueryBuilder`.

**Comment by joshua-obritsch** [comment]
I've also noticed this. Would be nice to be able to use joined queries.

**Comment by CSchank** [comment]
I need to learn a bit more about the underlying type system to support this, but I feel like it should be doable. Perhaps @mpscholten could guide me a bit or tell me if there are similar functions which can handle different types of `QueryBuilder`-type things.

**Comment by GarrisonJ** [comment]
Yeah, I don't understand either. 

But I do see this: https://github.com/digitallyinduced/ihp/blob/master/IHP/QueryBuilder.hs#L183 You can get the query builder out of a `JoinQueryBuilderWrapper` with the `getQueryBuilder` function.

**Comment by GarrisonJ** [comment]
Maybe this function https://github.com/digitallyinduced/ihp/blob/acddf9d4c535309ce5d02da945bfc556cad9f457/IHP/Pagination/ControllerFunctions.hs#L52 should take an instance of `HasQueryBuilder` instead of a `QueryBuilder` itself.

**Comment by CSchank** [comment]
Yes, I'll look into it. The second option is likely the most promising path forward.

**Comment by mpscholten** [comment]
This has been fixed by @CSchank on master :) You can follow https://ihp.digitallyinduced.com/Guide/updating.html to update to latest master :)

**Comment by CSchank** [comment]
@GarrisonJ Thanks for your idea, it worked perfectly! I didn't go general enough originally. Now, with this PR, it can work with anything that has `HasQueryBuilder`, which makes perfect sense since the `paginate` function only relies on `fetchCount` which has implementations for `HasQueryBuilder` data types, and I also fixed `filterList` to do the same, since it relies on `filterWhereIn`.
