### ISSUE TITLE
error screen: links style makes them hard to read

### ISSUE THREAD

**Issue by CSchank** [digitallyinduced/ihp#998]
I am guessing these are meant to have newlines or at least spaces between them. Might be a regression.

![image](https://user-images.githubusercontent.com/12722104/126812264-ea55ab02-8973-49f4-9356-1b1c436f8919.png)

**Comment by mpscholten** [comment]
I guess this only happens when you make a change that causes the compiling screen to be shown (e.g. a type or syntax error). Then the live reload will refresh the page, get's the error message and morphdoms to the new page. But it will not morphdom the `<head>` (only the body), so the css is not loaded as expected.

**Comment by mpscholten** [comment]
E.g. here's how this looks for me when I first start the app successfully and then insert a syntax error:

![image](https://user-images.githubusercontent.com/2072185/126860919-69fa4342-619d-44d7-9ff1-654d581c735b.png)

When I now do full page refresh, this is how it looks:

![image](https://user-images.githubusercontent.com/2072185/126860928-bbb996e9-f5ba-4a61-a133-1f64bf03f437.png)

**Comment by CSchank** [comment]
Yes, that's how the page looks if I do a full refresh. So, this is a morphdom problem? Is this related to my question on Gitter about how it interacts with other JS things, like Elm? It definitely seems a bit glitchy in certain edge cases.

**Comment by mpscholten** [comment]
Fixed 👍
